### PR TITLE
Add cardknox gateway

### PR DESCRIPTION
**Pull request by dlehren**
Hi,
this is Dovid from cardknox 
We would like to add cardknox to active merchant please log on to http://www.cardknox.com/developer-sign-up/ to receive test credentials for the remote unit tests
Thanks.

### CODE REVIEW

**Comment by dlehren** [comment]
If needed i will email the credentials privately

**Comment by ntalbott** [comment]
@dlehren I'll definitely need them to run the remote tests. Our *strong* preference, though, is if we can have some test credentials to check in, as it makes ongoing maintenance much smoother.

**Comment by ntalbott** [comment]
Whoops, just saw you pointed out where to get credentials. I'll grab them from there.

**Comment by ntalbott** [comment]
@dlehren is Cardknox a USAePay Transaction whitelabel? Looks very similar to https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/usa_epay_transaction.rb.

**Comment by dlehren** [comment]
Its a separate gateway i used usapay transaction amoung other gateways a guide

**Comment by dlehren** [comment]
@ntalbott we had the developer account setup, and sent privately to you.
please confirm the you received it .

**Comment by ntalbott** [comment]
@dlehren I've got it, will hopefully get to work on merging this this week. Thanks!

**Comment by dlehren** [comment]
@ntalbott Thanks!

**Comment by dlehren** [comment]
@ntalbott Thanks. I see you also cleaned up much appreciated!

**Pull request closed without merging**
