### PR TITLE
Add codes AQ, BQ, SX, and SS to list of countries and update SD numeric code

### PR DESCRIPTION
**Pull request by zxlin**
## Addition
These codes are a part of the ISO 3166-1 standard and thus should be
included in this listing of countries.

AQ is Antarctica - alpha3: ATA, numeric: 010
BQ is Bonaire, Sint Eustatius and Saba - alpha3: BES, numeric: 535
SX is Sint Maarten (Dutch Part) - alpha3: SXM, numeric: 534
SS is South Sudan - alpha3: SSD, numeric: 728

ISO3166 Links:
https://www.iso.org/obp/ui/#iso:code:3166:AQ
https://www.iso.org/obp/ui/#iso:code:3166:BQ
https://www.iso.org/obp/ui/#iso:code:3166:SX
https://www.iso.org/obp/ui/#iso:code:3166:SS

## Correction
The ISO corrected the Sudan numeric country code from 736 to 729
following the country's split into Sudan and South Sudan. This change
was enacted on 2011-08-09.

See change history: https://www.iso.org/obp/ui/#iso:code:3166:SD

### CODE REVIEW

**Comment by zxlin** [comment]
Can someone take a look at this please, it's 5 lines of change to the country code mappings, nothing different with the logic. We would love to be able to have these up to date country codes.

**Comment by timbeiko** [comment]
Sorry about the delay. LGTM. @aprofeit can you please have a quick look to be sure?

**Comment by aprofeit** [comment]
👍

**Comment by aprofeit** [comment]
👍

**Pull request closed without merging**
