### PR TITLE
Stripe: Add application fee only on non-EMV transactions

### PR DESCRIPTION
**Pull request by bizla**
For the EMV transaction API, it doesn't make sense to an application fee to be added on the capture, as it's established on the initial authorization. Stripe will barf if you attempt to apply a transaction fee on EMV capture. 

@abecevello @girasquid for review.

### CODE REVIEW

**Comment by girasquid** [comment]
Test?

**Comment by abecevello** [comment]
Looks fine. Needs a test.

**Comment by bizla** [comment]
Test added. Merging on :green_apple:

**Comment by girasquid** [comment]
:+1:

**Comment by bizla** [comment]
Closed via e54bef312b6aa9cb379825a8b7d9f0f291379469.

**Pull request closed without merging**
