### PR TITLE
mercury gateway default to partial auth deny

### PR DESCRIPTION
**Pull request by shulmang**
mercury gateway default to partial auth deny

### CODE REVIEW

**Comment by andrewpaliga** [comment]
Speaking with Mercury support I can verify that this is desired behaviour. Enabling Partial Auth will authorize the transaction for the remaining balance on the card. 

ex. You are buying something for $100 and there is only $50 left on the card. The transaction would be approved for $50 with Partial Auth tag passed, and declined with Partial Auth tag left out. 

I think the latter is a more sensible default.

Note that Partial Auth only applies to card present transactions. When Partial Auth is supported there are additional requirements on the POS software to handle these cases (prompt for payment completion etc.). 

@j-mutter @ntalbott do these changes look good?

**Comment by ntalbott** [comment]
Yup, in a CNP context, can't ever imagining wanting that to happen. :+1: for this change.

**Comment by j-mutter** [comment]
Tests? :innocent:

**Comment by ntalbott** [comment]
Implemented in https://github.com/activemerchant/active_merchant/commit/ebf1293228555c0e4d2512f61e1e89d6e44b59d2.

**Pull request closed without merging**
