### PR TITLE
[Bugfix] Stripe: Interpret string input to store method as token identifier

### PR DESCRIPTION
**Pull request by bizla**
Addresses #2130 

### Problem
We had an implicit and untested code path that allowed `StripeGateway` consumers to pass strings into `store` without headache. After https://github.com/activemerchant/active_merchant/commit/f2a7ea3ed298038529acce7552b733ade8f3bc90, the call to `card_brand` effectively disallowed string inputs, but no tests failed.

### Fix
Strings are interpreted (via if-else fallthrough) to be token identifiers in other methods like purchase, so this fix restores that behaviour by replacing the `card_brand` check, adds the ability to also pass in a `StripePaymentToken` for consistency, and the appropriate tests with some minor code cleanup along the way. 

Please review @timbeiko @aprofeit

### CODE REVIEW

**Comment by timbeiko** [comment]
LGTM 👍

**Comment by aprofeit** [comment]
Add _all_ the tests! 👍

**Comment by bizla** [comment]
Closed via 48b58efe660a9fc9522bc4d3fd8fb09c601c357c

**Comment by jordan-brough** [comment]
@bizla thanks for getting this fixed!

**Pull request closed without merging**
