### PR TITLE
Mercado Pago: Added more fields purchase requests.

### PR DESCRIPTION
**Pull request by DustinHaefele**
Added more options to the payer object if they are present, added
Metadata object if present. Checking for exact external_reference field
as a second option when setting

CE-843

Unit:
39 tests, 181 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Remote: The failed tests here are also failing for me on the master branch.
35 tests, 100 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
91.4286% passed

### CODE REVIEW

**Comment by DustinHaefele** [comment]
Couple thoughts for the reviewer.

- I put the explicit external reference field as the second option in the || statement to be sure that any current behavior stayed the same but I could go both ways on that.
- We were creating a payer object already so I merged the explicitly set payer object into that to perserve old functionality as well as add any fields to that that are explicitly passed in.
- The ticket requests aditional nested fields for the additional_info field but any field on additional info is already being passed on so I didn't see anything that needed updating on that.

**Comment by therufs** [comment]
Hey @DustinHaefele -- this seems like a good start. A couple of q's/things to clarify: 

- It looks like `metadata` gets returned in the live response; I'd like us make a unit test for that with an appropriate mock (something like `successful_purchase_with_metadata_response`). 
- The `test_successful_purchase_with_payer` test is failing for me with message `The name of the following parameters is wrong : [payer.phone, payer.identification.name]`. If you can't reproduce this, let me know and we can figure out why. :D

**Comment by DustinHaefele** [comment]
> Hey @DustinHaefele -- this seems like a good start. A couple of q's/things to clarify:
> 
> * It looks like `metadata` gets returned in the live response; I'd like us make a unit test for that with an appropriate mock (something like `successful_purchase_with_metadata_response`).
> * The `test_successful_purchase_with_payer` test is failing for me with message `The name of the following parameters is wrong : [payer.phone, payer.identification.name]`. If you can't reproduce this, let me know and we can figure out why. :D

Interesting, I was able to reproduce and fix but it didn't fail for me yesterday 🤷 .  Also added the unit test for the metadata field.

**Comment by therufs** [comment]
@DustinHaefele Well, that's why we do code review :D 

It looks like the MP test gateway is down right now :( but I'll try again in a bit. 

In the meantime, it looks like Rubocop (the linter AM uses) has a couple of complaints -- you can see them listed out by running `bundle exec rubocop`, or auto-fix the ones that can be auto-fixed with `bundle exec rubocop -a`.

**Comment by DustinHaefele** [comment]
> @DustinHaefele Well, that's why we do code review :D
> 
> It looks like the MP test gateway is down right now :( but I'll try again in a bit.
> 
> In the meantime, it looks like Rubocop (the linter AM uses) has a couple of complaints -- you can see them listed out by running `bundle exec rubocop`, or auto-fix the ones that can be auto-fixed with `bundle exec rubocop -a`.

Rubocop is happy now

**Review by therufs — APPROVED** [review]
lgtm && tests behave as expected!

**Pull request closed without merging**
