### PR TITLE
extra argument checking on custom fields, allow qty to be passed in a…

### PR DESCRIPTION
**Pull request by lancecarlson**
…ddition to quantity for the usaepay gateway

### CODE REVIEW

**Comment by lancecarlson** [comment]
I believe this is failing for the same reason this other PR is failing (same version of Ruby, irrelevant error message, etc):

https://github.com/activemerchant/active_merchant/pull/3089.

The PR itself should be fine.

**Comment by lancecarlson** [comment]
@curiousepic Is it possible to force re-run Travis again?

**Comment by nfarve** [comment]
@lancecarlson you should be able to force push and it will restart. Let me know when its passing and I will merge it.

**Comment by lancecarlson** [comment]
Looks like you're supposed to close and re-open to get it to rerun.

**Comment by lancecarlson** [comment]
@nfarve I'm not sure how to accomplish this! Assistance would be appreciated. haha

**Comment by nfarve** [comment]
looks like its 👍 now.

**Comment by nfarve** [comment]
You should be able to do a `git push -f origin <your branch name>`

**Pull request merged**
