### PR TITLE
S5: Add Store

### PR DESCRIPTION
**Pull request by anellis**

### CODE REVIEW

**Comment by anellis** [comment]
@duff addresses spreedly/core#1231

**Comment by duff** [comment]
@anellis In theory, we should also be able to run an auth/purchase using a card stored in the S5 vault.  Example: 

https://github.com/activemerchant/active_merchant/blob/master/test/remote/gateways/remote_pay_conex_test.rb#L148

**Comment by anellis** [comment]
@duff ah, sorry! Updated.

**Comment by duff** [comment]
:+1: :+1:

**Pull request closed without merging**
