### PR TITLE
Allow to use this gem with Rails 5

### PR DESCRIPTION
**Pull request by rafaelfranca**
The only required changes were to remove an unused require that was removed in Rails 5 and to change the gemspec to allow this gem to be installed with that version.

### CODE REVIEW

**Comment by rafaelfranca** [comment]
cc @duff

**Comment by ntalbott** [comment]
@rafaelfranca is Rails 5 released yet? Usually we don't add a new Rails version until it's in the wild.

**Comment by ntalbott** [comment]
@rafaelfranca if you're comfortable supporting it, :+1:.

**Comment by rafaelfranca** [comment]
Sure! I can support it.

**Comment by j-mutter** [comment]
:heart_eyes:

**Pull request closed without merging**
