### PR TITLE
Add support for dLocal installments

### PR DESCRIPTION
**Pull request by kdelemme**
**when applied this will**
Add support for creating a payment with installments with dLocal

```
remote tests
27 tests, 71 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

unit tests
18 tests, 71 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
```

### CODE REVIEW

**Comment by kdelemme** [comment]
I understand that you require a remote test that would create an [installments-plan](https://docs.dlocal.com/api-documentation/payins-api-reference/payments/credit-card-payments/installments#create-an-installments-plan) first, and then use this `installment_id` to make a purchase.

How would you handle the creation of the dLocal installments-plans? Would you recommend adding a public method `create_installments_plans(options)` in the dLocal gateway? 
Or would you make this API request directly from the test? If so do you have an example of such usage please?

Thanks

**Comment by therufs** [comment]
Hey @kdelemme -- sorry about the delay in getting back to you on this. I think it's fine to just send the request inline as part of the relevant test. There are a few examples here: https://github.com/activemerchant/active_merchant/blob/0dc710d3bb191044596aef2e4028432a5fdd3368/test/remote/gateways/remote_moneris_test.rb#L295 

Thanks much!

**Comment by kdelemme** [comment]
Hi @therufs, thanks for getting back to me.
I'm still confused about how I'm supposed to create an installments-plans from the gateway since it's not available via spreedly.

Basically I need to do the following:
1. POST `https://api.dlocal.com/installments-plans` with some params so I get back the installments-plans
2. Use the `gateway.purchase()` with the `{ installment_id, installments }` taken from the previous dLocal request.

I'm not sure how 1. should be done from the test since the dLocal gateway does not provide a method to create the installments-plans. 
How would you do this?

Thanks!

**Comment by therufs** [comment]
@kdelemme Oooh, I see. I misunderstood the flow for creating an installments plan initially, sorry about that! So long as creating the installments plan in the first place isn't being handled as part of this work, I think it's fine to just use a sample response (which seems like exactly what you did here). 

I'm going to request another reviewer, but I think this looks good!

**Comment by kdelemme** [comment]
Awesome thanks!

**Comment by cdnbacon** [comment]
@leila-alderman how will we know if this has been released to production and available for our use?

Thanks!

**Comment by leila-alderman** [comment]
@cdnbacon These fields are now in production and ready for use!

You can find them in our documentation now in [the dLocal gateway guide](https://docs.spreedly.com/payment-gateways/d-local/#optional-gateway-specific-fields) and [in our changelog](https://docs.spreedly.com/changelog/#support-gateway-specific-fields-for-dlocal).

Thanks for your help in getting this work done!

**Comment by cdnbacon** [comment]
This is great news, thanks @leila-alderman !

**Pull request closed without merging**
