### PR TITLE
MIGS redirect failures do not include SecureHash

### PR DESCRIPTION
**Pull request by adz**
You get a 'Secure Hash mismatch' on any error returned
by the gateway.

### CODE REVIEW

**Comment by alovak** [comment]
@adz is there a possibility to add test for this?

**Comment by alovak** [comment]
+1 for this PR

**Comment by adz** [comment]
@alovak Updated with a little test adjustment. It's strange in that the gateway is more lax in the case of failure, so made the test show the behaviour more explicitly.

**Comment by ntalbott** [comment]
Ugh, the credentials in the fixtures file have stopped working, so I can't test this. @mnoack originally supplied them, but I don't know if he has any ability to fix them. @adz do you have access to test credentials I can use to run the remote tests for this?

**Comment by jasonwebster** [comment]
Closing due to staleness. Feel free to reopen when the outstanding issues are resolved.

**Pull request closed without merging**
