### PR TITLE
add White gateway

### PR DESCRIPTION
**Pull request by alovak**

### CODE REVIEW

**Comment by yazinsai** [comment]
Adding a basic description on there: 

[White](https://whitepayments.com) is a payment solution for developing countries .. countries that have long been neglected by larger payment solutions. It's like Stripe, and is starting off in the Middle East before expanding to other developing regions soon.

**Comment by yazinsai** [comment]
+1

**Comment by yazinsai** [comment]
@ntalbott hi Nathaniel -- is active_merchant still alive?

**Comment by ntalbott** [comment]
@yazinsai for sure, but the maintainers have day jobs, and adding new gateways is non-trivial. We do eventually get to everything, but sometimes it takes months before we get a chance to clear out the backlog.

**Comment by yazinsai** [comment]
@ntalbott I can imagine -- is there anything we can do to help take some of that load off you guys, and thereby get requests approved quicker?

**Comment by ntalbott** [comment]
Hey folks, looks like White has been superseded by Payfort? Can I close this out?

**Comment by alovak** [comment]
yes. it can be closed. we (as Payfort) have a new solution, probably we will have to submit new PR :)

**Comment by ntalbott** [comment]
@alovak hopefully I can get to it faster this time!

**Pull request closed without merging**
