### PR TITLE
Ability to add metadata to authorize and purchase submissions to Fat Zebra

### PR DESCRIPTION
**Pull request by montdidier**

### CODE REVIEW

**Comment by montdidier** [comment]
When merging, I would imagine you'll want to squash.

**Comment by jknipp** [comment]
@montdidier Can you provide a remote test and squash/rebase?

**Comment by montdidier** [comment]
@jknipp how is that?

**Comment by jknipp** [comment]
@montdidier Looks good! I'll plan to merge this soon.

**Pull request closed without merging**
