### PR TITLE
Remove Barclays ePDQ MPI

### PR DESCRIPTION
**Pull request by bdewater**
At Shopify we're seeing 'connection refused' errors to the endpoint and after reaching out to their support it turns out that this product is not available to new accounts. It has been replaced by [ePDQ DirectLink](https://support.epdq.co.uk/en/guides/integration%20guides/directlink).

### CODE REVIEW

**Comment by elfassy** [comment]
should we close this PR?

**Comment by bdewater** [comment]
No, still valid.

**Comment by davidsantoso** [comment]
Thanks for the ping- 👍 on the Spreedly end.

**Comment by elfassy** [comment]
looks like we forgot to remove the remote tests for this gateway https://github.com/activemerchant/active_merchant/blob/master/test/remote/gateways/remote_barclays_epdq_test.rb. I'll open a PR

**Pull request merged**
