### PR TITLE
Pin Payments: add void support

### PR DESCRIPTION
**Pull request by montdidier**
Pin Payments supports void https://pinpayments.com/developers/api-reference/charges#void-charges

# Test Summary

## Unit

4931 tests, 74348 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

## Rubocop

716 files inspected, no offenses detected

## Remote

19 tests, 58 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

### CODE REVIEW

**Review by rachelkirk — CHANGES_REQUESTED** [review]
Hey @montdidier , could you add a `test_failed_void` as well? Thank you!

**Comment by montdidier** [comment]
@rachelkirk  added and updated test summary.

**Review by rachelkirk — CHANGES_REQUESTED** [review]
Hey @montdidier one more ask, please. Can you combine the changes from the updated countries PR with this one and rebase? This will help us avoid merge conflicts (I ran into that just now trying to rebase and update after I merged your first credit card PR). Thank you!

**Review by rachelkirk — CHANGES_REQUESTED** [review]
Hey @montdidier, can you combine the void PR with [this PR ](https://github.com/activemerchant/active_merchant/pull/4143/files) to help us avoid merge conflicts? Thanks!

**Comment by montdidier** [comment]
@rachelkirk should be done. let me know if you need anything else.

**Review by rachelkirk — APPROVED** [review]
Tests pass, looks good. Thanks for combing the PR's, we really appreciate it!

**Comment by curiousepic** [comment]
Thanks for handling this @rachelkirk

**Pull request merged**
