### PR TITLE
RedsysRest: Add support for 3DS

### PR DESCRIPTION
**Pull request by almalee24**
Unit:
23 tests, 101 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 100% passed

Remote:
18 tests, 38 assertions, 8 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications 55.5556% passed

### CODE REVIEW

**Comment by almalee24** [comment]
> Why are so many remote tests failing?

Looks like it could be use needing a new test card but I can't find a non 3DS one on their website

**Comment by aenand** [comment]
> > Why are so many remote tests failing?
> 
> Looks like it could be us needing a new test card but I can't find a non 3DS one on their website. I looks like maybe the test card that we're using is triggering a certain response but I'm not sure.

Hmmmm I think when I added these, if `DS_MERCHANT_DIRECTPAYMENT` was set to `true` it skipped 3DS. I wonder what the new test card value(s) are?

**Comment by aenand** [comment]
I see an AMEX card in their test env, i wonder if that one trigger 3DS?

**Comment by almalee24** [comment]
> I see an AMEX card in their test env, i wonder if that one trigger 3DS?

I'm not sure what AMEX card you're talking about

**Comment by almalee24** [comment]
> > > Why are so many remote tests failing?
> > 
> > 
> > Looks like it could be us needing a new test card but I can't find a non 3DS one on their website. I looks like maybe the test card that we're using is triggering a certain response but I'm not sure.
> 
> Hmmmm I think when I added these, if `DS_MERCHANT_DIRECTPAYMENT` was set to `true` it skipped 3DS. I wonder what the new test card value(s) are?

I looks like DS_MERCHANT_DIRECTPAYMENT is not working anymore. I'm not sure, I can't see anything in their documentation. Or maybe they're requiring 3DS for all transactions now?

**Review by bradbroge — APPROVED** [review]
Verified that the failing remote tests are failing with 
```
   @message="Requires SCA authentication"
```
So it is still expecting a 3DS transaction, and I didn't see an easy way to resolve that in the Redsys documentation.

**Pull request merged**
