### PR TITLE
Add support for nonce payment method to braintree blue gateway

### PR DESCRIPTION
**Pull request by cdion**
This change enables using the payment_method_nonce option available in the Braintree v zero API.

### CODE REVIEW

**Comment by kamui** [comment]
We're looking to support Braintree v.zero as well. Is something blocking this from getting merged?

**Comment by girasquid** [comment]
This change looks ok, but it can't be cleanly merged - can you rebase? Is there any possibility to get a remote test for this?

**Comment by cdion** [comment]
Will do.  Can I submit as a separate PR and close this one?

**Comment by girasquid** [comment]
Sorry for the delay on this - yes please. :)

**Pull request closed without merging**
