### PR TITLE
USA Epay Transaction: Scrub sensitive data

### PR DESCRIPTION
**Pull request by curiousepic**
Remote:
20 tests, 73 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Unit:
40 tests, 237 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

### CODE REVIEW

**Comment by curiousepic** [comment]
@dtykocki Mostly bang-for-buck while going through this batch of scrub additions, buuut I suppose it isn't _that_ much extra work to do them in tandem...

**Comment by dtykocki** [comment]
> Mostly bang-for-buck while going through this batch of scrub additions

That's fair, but I figure since we're improving the scrubs, we might as well ensure we have proper test coverage along the way.

**Comment by curiousepic** [comment]
@dtykocki Unit test added.

**Comment by curiousepic** [comment]
Updated, now with 💯% less track data exposed.

**Pull request closed without merging**
