### PR TITLE
Regenerated cacert.pem

### PR DESCRIPTION
**Pull request by guaguasi**
cacert.pem is extremely outdated, regenerated it using libcurl's `mk-ca-bundle.pl`. Should address #2657, #2614, and similar.

### CODE REVIEW

**Comment by rwdaigle** [comment]
There's been some discussion amongst @activemerchant/spreedly that we should remove the certs from the project itself all together, instead relying on the certificate management of each environment as is the default for almost all other projects.

Curious if @activemerchant/developers are using AM's certs or are already overriding with system certs?

**Comment by guaguasi** [comment]
Copying the system's ca-bundle was how I initially fixed my issue (#2657) before finding out how to regenerate the mozilla bundle file. I'm currently assigning the system bundle to the `CA_FILE` constant as a stop gap which seems to be working but is throwing a warning. It appears that currently it's still using AM's certs.

Personally, I feel it should use the environment's bundle by default with an up to date `cacert.pem`  file as a fallback, as well as a proper way to specify a custom location for a bundle.

**Comment by guaguasi** [comment]
@bpollack I can understand that. I literally just downloaded `certdata.txt` file the original `cacert.pem` was generated with and used `mk-ca-bundle.pl` to generate the `cacert.pem` in this PR. It should contain all the current certificates, right?

**Comment by varyonic** [comment]
I'm not a member of @activemerchant/developers and I was caught by surprise when the Digicert Global Root G2 cert expired yesterday, used to verify sermepa.es (Redsys). Took me a while first to update our old Ubuntu ca-certificates package and then to overwrite cacert.pem currently provided.  This is a small shop so not much attention paid here to managing certs at the Rails environment level.

**Comment by bpollack** [comment]
I'm going to close this for now; we're trying to figure out what to do internally, and I'm tracking various proposals in #2901.

**Pull request closed without merging**
