### PR TITLE
Remove gateway: CertoDirect

### PR DESCRIPTION
**Pull request by shiroginne**
CertoDirect doesn’t exist any longer 😵

### CODE REVIEW

**Comment by timbeiko** [comment]
LGTM. CertoDirect effectively does not exist anymore and all tests passing, nothing else removed. 
screen shot 2016-05-20 at 2 46 54 pm

ping @ThereExistsX @lyverovski

**Comment by timbeiko** [comment]
@ThereExistsX @aprofeit can you please review?

**Comment by aprofeit** [comment]
👍

**Comment by ThereExistsX** [comment]
🌈

**Pull request closed without merging**
