### PR TITLE
CyberSource: updating API version to 1.198 and fixing 3DS test

### PR DESCRIPTION
**Pull request by Heavyblade**
## Summary:

Updates the API version for CyberSource adapter to version 1.198 and fixes a couple of broken tests by updating the pares test token

Note: The is 1 failing remote test that corresponds to authentication failures because of the lack of a Latam-related account.

## Test Execution:

*Remote*
Finished in 101.297606 seconds.
115 tests, 594 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
99.1304% passed

*Unit*
Finished in 24.866962 seconds.
5212 tests, 75893 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

*RuboCop*
743 files inspected, no offenses detected

### CODE REVIEW

**Review by javierpedrozaing — COMMENTED** [review]
LGTM

**Review by curiousepic — CHANGES_REQUESTED** [review]
I'm getting a couple additional remote test failures, `test_successful_3ds_validate_authorize_request` and `test_successful_3ds_validate_purchase_request`, both expecting a `reasonCode` of `100` but getting `476`.

@javierpedrozaing since Cristian is out for a while, maybe you can take a look and modify? Otherwise this looks good.

**Comment by Heavyblade** [comment]
@curiousepic that happens because the PARES used for the response is expired, to properly run those couple of tests you need to update the PARES using the documentation available on the[ PARES test](https://github.com/activemerchant/active_merchant/pull/4456/files#diff-4f2872b3007d95609b45a6bdead0fbb09fc667b8a556e034bb67e00a97e6cb41R915)

**Review by curiousepic — APPROVED** [review]
Gotcha, thanks for the explanation. Will merge soon.

**Pull request closed without merging**
