### PR TITLE
Update EBANX API URL

### PR DESCRIPTION
**Pull request by vnbrs**
Hi, I'm Vinicius, from EBANX!

We're migrating our API base URL, as you can see here https://github.com/ebanx-integration/ebanx-ruby/commit/d87f5ffcc3912ead5938b738bac57f921fd0b1dd

This PR updates the API base URL to our new one.

### CODE REVIEW

**Comment by vnbrs** [comment]
Can we have this merged? 😄

**Comment by nfarve** [comment]
@vnbrs do you have successful remote test I can add to the merge? Unit tests worked fine locally.

**Comment by vnbrs** [comment]
Yes! We're using these new URLs on our official integration libraries

**Comment by nfarve** [comment]
@vnbrs I am more so looking for text similar to what can be found in most of commits. Showing successful unit and remote tests run for the gateway: 

https://github.com/activemerchant/active_merchant/commit/99db685a6940b1ba5f6d00047e9d908a5330fcd0

**Comment by bpollack** [comment]
Thanks! I added unit and test output. Remotes look fine, other than some breakage not related to this. (We'd be happy to take a PR to fix that, too, @vnbrs.) Merged.

**Pull request closed without merging**
