### PR TITLE
Element express terminal values

### PR DESCRIPTION
**Pull request by asanger**
If no options are passed, everything works exactly as normal. If any options _are_ passed, they will be populated in the defined locations.

This change was made to get us past "certification" with ElementExpress. Instead of passing the default values of the modified lines, we were required to pass in values based on the specific use case.

### CODE REVIEW

**Comment by asanger** [comment]
As my project moved into a production state, I noticed that the original author had mistyped the production URL - as it stands in master, nobody will be able to use this in production. My last commit corrects this. If you would like that commit moved to a separate PR, please let me know and I will be happy to do so.

**Comment by asanger** [comment]
There has been a typo in the Element Express production endpoint (in master) for well over a year now. 

https://service.elementexpress.com/express.asmx does not exist.
https://services.elementexpress.com/express.asmx is the correct endpoint.

This PR fixes that, and until the fix is made, nobody will be able to use this in production. Any chance we could get this merged?

**Comment by davidsantoso** [comment]
Hi @asanger - I'm grooming old pull requests and if this is still something you're interested in, please:

1. Reopen the PR
2. Rebase on `master`
3. Squash all commits
4. Tag me for review

Thanks!

**Comment by yjukaku** [comment]
@asanger Do you mind rebasing and reopening this PR?

**Comment by asanger** [comment]
feel free! Thanks

**Comment by asanger** [comment]
hah, sorry @yjukaku I totally thought you were offering to do it 🙈  I'll get this submitted shortly!

**Pull request closed without merging**
