### PR TITLE
RuboCop: various fixes

### PR DESCRIPTION
**Pull request by bpollack**

### CODE REVIEW

**Comment by bpollack** [comment]
This may be too big; 203 files were touched, and while most only have literally a couple lines being altered, the final diff is still relatively large (500 lines, unsurprisingly, or a bit over double the file count). I'm happy to break this into multiple PRs, but we're getting to where some of the changes are just kind of pervasive.

**Comment by bpollack** [comment]
@activemerchant/spreedly-endpoints Ping. If this is too big, I'm happy to break it up, but it's gonna bitrot if it sits too much longer. I already had to rebase and clean up a bit.

**Comment by nfarve** [comment]
Its personally daunting to me to try and remove at its current size.

**Comment by bpollack** [comment]
All right, I'll break it up.

**Pull request closed without merging**
