### PR TITLE
Initial draft for clearhaus gateway

### PR DESCRIPTION
**Pull request by dinesh**
This PR supports Denmark based gateway [Clearhaus gateway](http://clearhaus.com/). It has support for 3d authorization and singed request ( optionally ) which should be reviewed carefully.

Let me know if you have any questions.

### CODE REVIEW

**Comment by x2q** [comment]
+1

**Comment by ianmurrays** [comment]
:+1:

**Comment by RikkeG** [comment]
+1

**Comment by ntalbott** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;au8sNjEl&#x2F;103-clearhaus-pin"> Clearhaus - Pin</a>

**Pull request closed without merging**
