### PR TITLE
Adding Oauth Response for access tokens

### PR DESCRIPTION
**Pull request by almalee24**
Add new OAuth Response error handling to PayTrace, Quickbooks, Simetrik, Alelo, CheckoutV2 and Airwallex.

### CODE REVIEW

**Comment by aenand** [comment]
Why did this need to be reverted? You can also share the details in Slack if it's related to something outside of AM!

**Comment by BritneyS** [comment]
> Why did this need to be reverted? You can also share the details in Slack if it's related to something outside of AM!

➕ 1 to the above!

**Comment by almalee24** [comment]
@aenand @BritneyS Yes the issues its outside AM. I'm working to fix that on our side and adding test for each of these gateways. I'll tag y'all when I create a PR.

**Review by aenand — APPROVED** [review]
LGTM 🚀

**Pull request merged**
