### PR TITLE
Rubocop: Layout/CaseIndention and Layout/ElseAlignment

### PR DESCRIPTION
**Pull request by nfarve**
Fixes some issues with indention and alignment with cases and elses.

### CODE REVIEW

**Comment by bpollack** [comment]
Hmm, looks like we [_can_](https://rubocop.readthedocs.io/en/latest/cops_layout/#layoutcaseindentation); that's done by setting `IndentOneStep` to `true`. How do y'all feel about that, though? Having `when` flush with `case` is the default RuboCop style, but IMVHO it makes them harder to follow.

**Comment by curiousepic** [comment]
Honestly the indented `if`s are more annoying to me... not a strong opinion though.

**Comment by bpollack** [comment]
> Honestly the super-indented ifs are more annoying to me... 

This is why I haven't tried to land `Layout/ElseAlignment` in AM; we do this pattern so often there that it actually then overloads the line length limits. But I don't know an equivalent of `EnforceStyle: end` for `else` alignment.

**Comment by nfarve** [comment]
@bpollack there is no equivalent for `Layout/ElseAlignment`. We would just have to agree to ignore it all together.

**Comment by nfarve** [comment]
Also not sure I am on board for the indent on the `when`. I see your point that its a happy medium between the indent with the `=` or with the end.

**Comment by bpollack** [comment]
@nfarve Do you still want to merge this as-is? It's drifted enough from `master` I'm getting worried about it merging cleanly.

**Pull request merged**
