### PR TITLE
App55: Remove Gateway

### PR DESCRIPTION
**Pull request by ThereExistsX**
The App55 Gateway is dead, this PR removes App55 from Active Merchant.

* https://www.crunchbase.com/organization/app55#/entity
* http://www.app55.com/

**Attn:**
@girasquid @aprofeit

### CODE REVIEW

**Comment by aprofeit** [comment]
:+1:

**Comment by ThereExistsX** [comment]
@masaruhoshi @matthelm

**Comment by ThereExistsX** [comment]
@girasquid

**Comment by girasquid** [comment]
:+1:

**Pull request closed without merging**
