### PR TITLE
Bridgepay: Add echeck support

### PR DESCRIPTION
**Pull request by davidsantoso**
@duff and/or @rwdaigle: This adds eCheck support to the Bridgepay gateway.

Let me know if you have any thoughts/questions/concerns.

### CODE REVIEW

**Comment by rwdaigle** [comment]
All around looks great! Few comments:

* I'd use this as an opportunity to add a `scrub` method. Add account/routing number to that scrubbing if that's how other adapters work too?
* Does Bridgepay support storing the card? If so, we should use this as an opp. to add `store` as well.

**Comment by davidsantoso** [comment]
Ahhh good catch with the scrub- definitely needs to be updated (I think)!

I just checked the PDF docs and they don't currently support `store` so I think we're ok on that end.

**Comment by davidsantoso** [comment]
@rwdaigle ready for round 2.

**Comment by rwdaigle** [comment]
Unit tests:

```
Finished in 14.523776 seconds.
--------------------------------------------------------------------------------
3041 tests, 14123 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
--------------------------------------------------------------------------------
209.38 tests/s, 972.41 assertions/s
```

Remote tests:

```
Finished in 37.505004 seconds.
--------------------------------------------------------------------------------
16 tests, 37 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
--------------------------------------------------------------------------------
0.43 tests/s, 0.99 assertions/s
```

**Pull request closed without merging**
