### PR TITLE
Litle - Add support for Auth & Sale with Paypage Registration ID

### PR DESCRIPTION
**Pull request by deakolt**
The Litle API supports making authorizations and sales using a Paypage Registration ID instead of a LitleToken or a credit card.  This PR adds support for that.

Changes:
-Add `LitlePaypageRegistration` to wrap the requisite data for a request using a Paypage Registration ID
-Modify `add_payment_method` to add XML for a Paypage XML block
-Make `name` element of `billToAddress` element optional (This is consistent with the current Litle XML Schema)
-Add test cases to `litle_test.rb` and `remote_litle_test.rb`

### CODE REVIEW

**Comment by deakolt** [comment]
@anellis @ntalbott @duff 
We would love feedback from you guys!

**Comment by steveklebanoff** [comment]
@anellis @ntalbott @duff @girasquid Any feedback on this?  We would love to have this change merged so we don't need to rely on a custom fork or roll this functionality ourselves outside activemerchant.

**Comment by anthonyagresta** [comment]
:+1:

**Comment by jasonwebster** [comment]
Closing due to staleness. Feel free to reopen when the outstanding issues are resolved.

**Comment by elskwid** [comment]
Hi @jasonwebster. I believe there were some auto-closed PRs recently. This PR doesn't have any feedback from maintainers and, as a user of Litle/Vantiv, I am interested in the functionality. 

Is there a way to re-open the PR and discuss the changes?

Thanks!

**Comment by steveklebanoff** [comment]
@elskwid this has been rebased and updated, new PR: https://github.com/activemerchant/active_merchant/pull/2513

**Pull request closed without merging**
