### PR TITLE
Safe Charge: Support string for Add sg_NotUseCVV field

### PR DESCRIPTION
**Pull request by ajawadmirza**
String parameter support is added for sg_NotUseCVV field

CE-2084

Rubocop:
723 files inspected, no offenses detected

Unit:
4977 tests, 74599 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Remote:
30 tests, 81 assertions, 1 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
96.6667% passed

### CODE REVIEW

**Review by jessiagee — APPROVED** [review]
Failing test is `test_successful_regular_purchase_through_3ds_flow_with_invalid_pa_res` which is the same on master, everything passes otherwise and this looks good 👍🏻

**Review by dsmcclain — CHANGES_REQUESTED** [review]
I don't think this change is quite right.

Here is a modified version of the test in`test/unit/gateways/safe_charge_test.rb` to cover cases where the `not_use_cvv` param is a string, or cases where it is `false`:

```
def test_successful_authorize_with_not_use_cvv
  stub_comms do
    @gateway.authorize(@amount, @credit_card, @options.merge({ not_use_cvv: true }))
  end.check_request do |_endpoint, data, _headers|
    assert_match(/sg_NotUseCVV=1/, data)
  end.respond_with(successful_authorize_response)

  stub_comms do
    @gateway.authorize(@amount, @credit_card, @options.merge({ not_use_cvv: 'true' }))
  end.check_request do |_endpoint, data, _headers|
    assert_match(/sg_NotUseCVV=1/, data)
  end.respond_with(successful_authorize_response)

  stub_comms do
    @gateway.authorize(@amount, @credit_card, @options.merge({ not_use_cvv: false }))
  end.check_request do |_endpoint, data, _headers|
    assert_match(/sg_NotUseCVV=0/, data)
  end.respond_with(successful_authorize_response)
end
```
This test fails when the field is `'true'` and when it is `false`.

I think the line should be changed to:

`post[:sg_NotUseCVV] = options[:not_use_cvv] ? 1 : 0`

Then everything passes.

**Comment by jessiagee** [comment]
> I don't think this change is quite right.
> 
> Here is a modified version of the test in`test/unit/gateways/safe_charge_test.rb` to cover cases where the `not_use_cvv` param is a string, or cases where it is `false`:
> 
> ```
> def test_successful_authorize_with_not_use_cvv
>   stub_comms do
>     @gateway.authorize(@amount, @credit_card, @options.merge({ not_use_cvv: true }))
>   end.check_request do |_endpoint, data, _headers|
>     assert_match(/sg_NotUseCVV=1/, data)
>   end.respond_with(successful_authorize_response)
> 
>   stub_comms do
>     @gateway.authorize(@amount, @credit_card, @options.merge({ not_use_cvv: 'true' }))
>   end.check_request do |_endpoint, data, _headers|
>     assert_match(/sg_NotUseCVV=1/, data)
>   end.respond_with(successful_authorize_response)
> 
>   stub_comms do
>     @gateway.authorize(@amount, @credit_card, @options.merge({ not_use_cvv: false }))
>   end.check_request do |_endpoint, data, _headers|
>     assert_match(/sg_NotUseCVV=0/, data)
>   end.respond_with(successful_authorize_response)
> end
> ```
> 
> This test fails when the field is `'true'` and when it is `false`.
> 
> I think the line should be changed to:
> 
> `post[:sg_NotUseCVV] = options[:not_use_cvv] ? 1 : 0`
> 
> Then everything passes.

Ahh okay I understand your question better now - yeah I had the same thought ("what if it's a string?") and should have been more diligent in my review. Thanks for catching that and updating @dsmcclain !

@ajawadmirza please update the code to follow up on Dylan's point above, and also rebase once you've got that changed. Thank you!

**Comment by ajawadmirza** [comment]
> > I don't think this change is quite right.
> > Here is a modified version of the test in`test/unit/gateways/safe_charge_test.rb` to cover cases where the `not_use_cvv` param is a string, or cases where it is `false`:
> > ```
> > def test_successful_authorize_with_not_use_cvv
> >   stub_comms do
> >     @gateway.authorize(@amount, @credit_card, @options.merge({ not_use_cvv: true }))
> >   end.check_request do |_endpoint, data, _headers|
> >     assert_match(/sg_NotUseCVV=1/, data)
> >   end.respond_with(successful_authorize_response)
> > 
> >   stub_comms do
> >     @gateway.authorize(@amount, @credit_card, @options.merge({ not_use_cvv: 'true' }))
> >   end.check_request do |_endpoint, data, _headers|
> >     assert_match(/sg_NotUseCVV=1/, data)
> >   end.respond_with(successful_authorize_response)
> > 
> >   stub_comms do
> >     @gateway.authorize(@amount, @credit_card, @options.merge({ not_use_cvv: false }))
> >   end.check_request do |_endpoint, data, _headers|
> >     assert_match(/sg_NotUseCVV=0/, data)
> >   end.respond_with(successful_authorize_response)
> > end
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This test fails when the field is `'true'` and when it is `false`.
> > I think the line should be changed to:
> > `post[:sg_NotUseCVV] = options[:not_use_cvv] ? 1 : 0`
> > Then everything passes.
> 
> Ahh okay I understand your question better now - yeah I had the same thought ("what if it's a string?") and should have been more diligent in my review. Thanks for catching that and updating @dsmcclain !
> 
> @ajawadmirza please update the code to follow up on Dylan's point above, and also rebase once you've got that changed. Thank you!

ah yes that was a good catch @dsmcclain . I am making the update for this change :)

**Review by dsmcclain — APPROVED** [review]
Tests passing, thank you for updating it.

**Pull request merged**
