### PR TITLE
CardStream: Make Void call Cancel instead of Refund

### PR DESCRIPTION
**Pull request by curiousepic**
Also corrects some remote test cases from `authorize and refund` to `purchase and refund` 

@duff to confirm and merge

### CODE REVIEW

**Comment by duff** [comment]
This is looking good!  I'd recommend running `rake` for the active merchant project to run all the unit tests.  This shows warnings that don't show when running individual tests.  Not sure why.

You'll see that there's 2 warnings this PR causes.  Once you push the fixes for those, we ought to be good to go.

**Comment by curiousepic** [comment]
@duff Strange. I get no failures or errors with `be rake test:units`. AM is up to date. What command do you use, exactly, and what were the errors?

**Comment by duff** [comment]
Warnings in the terminal:

```
[ ~/code/active_merchant ] master !
✦  rake
/Users/duff/.rbenv/versions/2.2.0/bin/ruby -I"lib:test" -rubygems -w  "/Users/duff/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/rake_test_loader.rb" "test/unit/**/*_test.rb"
/Users/duff/code/active_merchant/test/unit/gateways/card_stream_test.rb:250: warning: method redefined; discarding old successful_void_response
/Users/duff/code/active_merchant/test/unit/gateways/card_stream_test.rb:238: warning: previous definition of successful_void_response was here
Loaded suite /Users/duff/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/gems/rake-10.4.2/lib/rake/rake_test_loader
Started
.....................................................................................................................................................................................
```

**Comment by curiousepic** [comment]
@duff Ah, got it. PR updated.

**Pull request closed without merging**
