### PR TITLE
Merchant Ware v4: Add support for verify

### PR DESCRIPTION
**Pull request by davidsantoso**
@duff: quick addition to the Merchant Ware version 4 adapter to add support for the verify action.

### CODE REVIEW

**Comment by duff** [comment]
@davidsantoso We usually have a unit test or two as well.

**Comment by duff** [comment]
The unit test's value can seem dubious, but when other folks don't have remote credentials, perhaps they provide value.

**Comment by davidsantoso** [comment]
Ah right. Alrighty, adding!

**Comment by davidsantoso** [comment]
@duff alrighty, added `verify` unit tests. Let me know if there's anything else missing.

**Comment by duff** [comment]
@davidsantoso :+1:

**Pull request closed without merging**
