### PR TITLE
Authentication for HTTP requests through proxy

### PR DESCRIPTION
**Pull request by cristianstanescu**
Allow passing a user and a password along address and port for proxies.

Remove previous :proxy_address and :proxy_port accessors and replace them with :proxy, a Ruby URI String to be parsed for proxy information.

### CODE REVIEW

**Comment by ntalbott** [comment]
This seems reasonable, but would need to be implemented in a backwards-compatible way. Thanks!

**Comment by cristianstanescu** [comment]
Thank you for your quick review.

I see what you mean about backwards-compatibility. I thought of it that way initially, but there were two reasons I figured for doing it this way in the end:

1. Laziness, as it seemed to me useless duplication, a little too much too write and work with something like this:

  ```ruby
  proxy_uri = URI.parse(ENV['PAYMENT_GATEWAY_PROXY'])

  gateway = ActiveMerchant::Billing::SagePayGateway.new
  gateway.proxy_address = proxy_uri.host
  gateway.proxy_port = proxy_uri.port
  gateway.proxy_user = proxy_uri.user
  gateway.proxy_password = proxy_uri.password
  ```

  vs.

  ```ruby
  gateway = ActiveMerchant::Billing::SagePayGateway.new
  gateway.proxy = ENV['PAYMENT_GATEWAY_PROXY']
  ```

2. I saw that `@endpoint` used in https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/connection.rb#L37 is also looking for a String/URI and seemed more consistent passing the `proxy` this way also.

---

These being the reasons, and not being familiar with the code and recommendations in Activemerchant, for backward compatibility, should I favor:

A. Keep `:proxy_address`, `:proxy_port` and add `:proxy_user` and `:proxy_password` as in the first example

B. Keep `:proxy_address`, `:proxy_port` and add `:proxy` as a String to be parsed as an URI and extract the data from there if it's given rather than `:proxy_address` and `:proxy_port`.

I would go for **B**, but I guess it's better to ask first.

**Comment by cristianstanescu** [comment]
@ntalbott this should now be backward compatible.

I've seen just a small thing after pushing. I've modified  the whitespace on this line by accident: https://github.com/activemerchant/active_merchant/pull/1894/files#diff-9f78979036d6e1787f93f58cf3ea6e34R65 Is it ok or should I commit a change to take it back? Thanks.

**Comment by cristianstanescu** [comment]
@ntalbott Could you please have another look at this one? Thank you.

**Comment by jasonwebster** [comment]
Closing due to staleness. Feel free to reopen when the outstanding issues are resolved.

**Pull request closed without merging**
