### PR TITLE
World Net TPS Gateway

### PR DESCRIPTION
**Pull request by varyonic**
New gateway for World Net TPS, http://worldnettps.com/

### CODE REVIEW

**Comment by bruno** [comment]
@varyonic looks good ... the `store` method is not implemented, was that intentional?

**Comment by varyonic** [comment]
Hi @bruno, we don't use that feature, but you can fork and add, or I will try and find some time to look at it.  I did something similar for Redsys.

**Comment by bruno** [comment]
Thanks @varyonic ... I will be working on it this week or next ... I will add it to your fork as a branch and PR it for you to add it to the current one if you deem it acceptable.

**Comment by varyonic** [comment]
@rwdaigle This branch is six months old now, shall I rebase?

**Comment by rwdaigle** [comment]
@varyonic pls do

**Comment by varyonic** [comment]
@rwdaigle Done.  Credentials for public test account included so running remote test should be straightforward.

**Pull request closed without merging**
