### PR TITLE
Pass card owner when storing tokenized cards

### PR DESCRIPTION
**Pull request by alexdunae**
Per issue #3006 -- Beanstream requires `trnCardOwner` when storing a tokenized credit card.

### CODE REVIEW

**Comment by yosukehasumi** [comment]
bump

**Comment by alexdunae** [comment]
Is there any chance of getting this merged?

**Comment by alexdunae** [comment]
Is there any chance of getting this merged? @filipebarcos

**Comment by filipebarcos** [comment]
@alexdunae Can you fix the conflicts, please?

**Comment by alexdunae** [comment]
@filipebarcos done, and thanks.

While I have you, the Beanstream/Bambora has long since moved from the current XML-based API currently in ActiveMerchant to a [REST-ish JSON API](https://dev.na.bambora.com/docs/references/payment_APIs/v1-0-5/).  The old API isn't even listed on their docs site anymore.

We'd be willing to update the integration to support their new API, but I wanted to check-in to see a) if you'd have any interest in merging it and b) what that process would look like.

One thought is that the old integration could remain as "Beanstream" and the new one could be listed as "Bambora" (which is the current name of the company after some acquisitions).

Happy to move this discussion to an issue or elsewhere....

**Comment by alexdunae** [comment]
@filipebarcos friendly bump on this -- should be mergeable again

**Pull request merged**
