### PR TITLE
Fix Securionpay supported countries list and add Trexle gateway

### PR DESCRIPTION
**Pull request by hossamhossny**
Securionpay does actually support only 39 countries out of the one listed here as you can see https://snag.gy/tNaYQU.jpg. This PR fixes Securionpay supported countries list and add Trexle gateway.

### CODE REVIEW

**Comment by hossamhossny** [comment]
@davidsantoso Please review this when you have a chance.

**Comment by hossamhossny** [comment]
@davidsantoso @curiousepic @jasonwebster 
Can someone take a quick look at this?

**Comment by hossamhossny** [comment]
@bpollack Can you merge please?

**Comment by bpollack** [comment]
@hossamhossny I'm not a member of Active Merchant anymore; haven't been for almost a year at this point.

**Comment by curiousepic** [comment]
@hossamhossny I'll merge soon, thanks.

**Comment by curiousepic** [comment]
@hossamhossny In fact, would you mind updating [SecurionPay's supported countries list in the actual adapter](https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/securion_pay.rb#L7-L8) to match this list as well?

**Comment by hossamhossny** [comment]
@curiousepic Happy to do it. Any idea why `git commit -amment` gives a conflict on the adapter file?

**Comment by hossamhossny** [comment]
@curiousepic Done. How do we clean the mess? :D

**Comment by curiousepic** [comment]
@hossamhossny done!

**Pull request closed without merging**
