### PR TITLE
Add Genesis Gateways

### PR DESCRIPTION
**Pull request by dimitrovv**
* Add support for **Genesis Gateways**
   * Integrate [`eMerchantPay Direct`](https://www.emerchantpay.com/) Gateway
   * Integrate [`E-ComProcessing Direct`](https://www.e-comprocessing.com/) Gateway

### CODE REVIEW

**Comment by dimitrovv** [comment]
@jasonwebster @davidsantoso this PR is ready for review

**Comment by davidsantoso** [comment]
@dimitrovv thanks for the PR! A couple things- gateways added to Active Merchant generally follow a structure of a gateway adapter, remote tests, and unit tests. This PR is a bit out of the expected file structure with including helper files and breaking out the tests. See our [wiki page on contributing a gateway](https://github.com/activemerchant/active_merchant/wiki/Contributing) for more details. Unfortunately we won't be adding these adapters until they fall in line with our conventions. 

We do appreciate new gateway adapters so if you're still interested in adding them please open a new pull request utilizing the gateway patterns as outlined in contribution wiki. If anything in the wiki is unclear, feel free to open an issue to discuss.

**Comment by dimitrovv** [comment]
@davidsantoso thanks for the update.

> A couple things- gateways added to Active Merchant generally follow a structure of a gateway adapter, remote tests, and unit tests. This PR is a bit out of the expected file structure with including helper files and breaking out the tests.

We decided to separate our integration into modules and helper classes, because the gateway class should have become large and would have been difficult for review and etc. 

I have read the [wiki page for contributing](https://github.com/activemerchant/active_merchant/wiki/Contributing), before starting with the development. I have also paid attention to the `breantree` and `paypal` integrations, they also use helper classes for their gateway integrations.

Do you mean that we should organize our integration into 3 files:
* **Gateway Class** - inherits from [Gateway Class](https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateway.rb)  
* **Remote Tests** - include all test cases without using shared examples in modules
* **Unit Tests** - include all test cases without using shared examples in modules

**Comment by davidsantoso** [comment]
> I have also paid attention to the breantree and paypal integrations, they also use helper classes for their gateway integrations.

Yes, I apologize- those are certainly special cases to some extent. The preference is that gateways not follow that pattern unless really necessary so we don't have too many extra helper files everywhere. I can be a bit difficult to parse through all of it! I will say, it's ok if two gateways share the exact same behavior or one is a while label of another, etc. We do have gateways that only change meta data so they include another gateway to keep things DRY. Mastercard/TNS/Citrus Pay are a good example.

> Do you mean that we should organize our integration into 3 files:
> 
> Gateway Class - inherits from Gateway Class
> Remote Tests - include all test cases without using shared examples in modules
> Unit Tests - include all test cases without using shared examples in modules

Yes. Also if it's two gateways then there would be 6 files total.

Thanks!

**Comment by dimitrovv** [comment]
@davidsantoso thanks for the details, the integrations will be restructured and then submitted

**Pull request closed without merging**
