### PR TITLE
Changing PayU Argentina minimum payment amount

### PR DESCRIPTION
**Pull request by Shelvak**
Now PayU request a minimum of 5 Argentine pesos. Fixing the amount and tests.

```
rake test:units
3857 tests, 67882 assertions, 0 failures, 0 errors, 0 pendings, 2 omissions, 0 notifications                                                                                 
100% passed

rake test:remote TEST=test/remote/gateways/remote_payu_latam_test.rb
30 tests, 74 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications                                                                                       
100% passed

### CODE REVIEW

**Comment by Shelvak** [comment]
@curiousepic , @dtykocki  Sorry to bother you, could you check or add any reviewer to this please?
Thanks in advance :)

**Comment by bpollack** [comment]
@Shelvak I apologize for asking this, but we're a bit overloaded. I'm trying to clean up a bunch of old PRs; this one looks good for merge, but would you mind linking me to the docs where the minimum changed so I can verify?

**Comment by Shelvak** [comment]
Hi Ben, thanks for the answer. I didn't find the official minimum amount. I asked in the forum but no answer yet, anyway I changed that because at least in sandbox the test fails with less than 5 Argentine$. I don't know if that was always in that way and in Prod the min is $17 or not. Waiting for the PayU official answer...

**Comment by bpollack** [comment]
Thanks @Shelvak . I'll leave this open for a bit, but if we can't get official confirmation, I'd rather leave this patch out and rely on users to know the minimum instead of enforcing an erroneous constraint in the library.

**Comment by bpollack** [comment]
Hi @Shelvak , did you find anything else in the docs? If not, would you mind if I closed this out, per above?

**Comment by Shelvak** [comment]
Hey @bpollack Sorry for the delay, I saw the comment and I totally forget about it....
No, I didn't find specific info about that. And I don't have a production account to test in Argentina. 
Let's close that and If I can check that in prod or get any official answer I'll reopen (and update :+1:)

**Pull request closed without merging**
