### PR TITLE
Remove payments-dev from the travis build email notifications

### PR DESCRIPTION
**Pull request by AnotherJoSmith**
There are about twenty people on this mailing list who receive theses emails.

@timbeiko @elfassy Any issues with this? You can add your own emails if you care about receiving them.

### CODE REVIEW

**Comment by timbeiko** [comment]
@AnotherJoSmith nope, please remove us :-D

**Comment by AnotherJoSmith** [comment]
I don't have merge access, so whenever you can do it! 5=t wuld b

**Comment by timbeiko** [comment]
My bad. Done @AnotherJoSmith !

**Comment by AnotherJoSmith** [comment]
Thanks Tim!

**Comment by elfassy** [comment]
🌈 !

**Pull request closed without merging**
