### PR TITLE
Adyen: Add RecurringProcessingModel

### PR DESCRIPTION
**Pull request by nfarve**
With visa updates, Adyen now requires the type of recurring processing
model for all recurring transactions. This adds the neccessary field.

Loaded suite test/remote/gateways/remote_adyen_test
..................................

34 tests, 86 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Loaded suite test/unit/gateways/adyen_test
......................

22 tests, 102 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

### CODE REVIEW

**Comment by curiousepic** [comment]
Looks like this is added only for Store actions, but I think these visa card on file designations need to be sendable for any type of transaction that involves a card stored elsewhere?

**Comment by nfarve** [comment]
@curiousepic from the post, it looks like this only applies to recurring transactions which are stored cards: https://www.adyen.com/blog/update-on-visas-new-card-on-file-transaction-type

**Comment by curiousepic** [comment]
@nfarve I don't think recurring in this case strictly means cards stored at Adyen... LMK if you want to chat to clarify.

**Comment by nfarve** [comment]
Hmm Let me know think about it some more then. Whats throwing me off is this statement: 
`By default Adyen will flag recurring transactions as 'subscription'. `

**Comment by nfarve** [comment]
@curiousepic It looks like the only place it could be added is for recurring transactions, which we don't seem to currently support. https://docs.adyen.com/developers/api-reference/recurring-api

**Comment by curiousepic** [comment]
Hmmmmm. Well, `store` does currently utilizes https://docs.adyen.com/developers/features/recurring-payments/store-payment-details
It would be nice if they defined "recurring" a little more explicitly in their post.

**Comment by curiousepic** [comment]
Their docs show the field is supported for auth/purches: https://docs.adyen.com/developers/api-reference/payments-api#paymentrequest 
This makes me think it should be passable with any transaction, not just when storing a card with Adyen.

**Comment by nfarve** [comment]
@curiousepic okay moved to `add_invoice`

**Comment by nfarve** [comment]
@curiousepic It did. Fixed

**Pull request merged**
