### PR TITLE
Add Zeus gateway

### PR DESCRIPTION
**Pull request by ShubhamGupta**
A Japanese payment gateway. http://www.cardservice.co.jp/

Need credentials for remote tests.

### CODE REVIEW

**Comment by ShubhamGupta** [comment]
@ntalbott Can you please review this once and let me know if we are good to go on this one. I have added test credentials for now.

**Comment by johnnyshields** [comment]
:+1: Please add this

**Comment by ntalbott** [comment]
@ShubhamGupta "quickcharge" is outside of scope for ActiveMerchant - can you remove?

Also, running the remote tests, everything seems to work except `test_successful_authorize`/`test_failed_capture`/`test_successful_authorize` - do those pass for you?

**Comment by ShubhamGupta** [comment]
@ntalbott Thanks for reviewing the code. I have removed the `quickcharge` option. Also, all remote tests are passing for me. I am on ruby 2.1.3. Can you add some backtrace so I can try and fix it?

**Comment by ntalbott** [comment]
Sure:

```
~/src/active_merchant git:(master 3↑)$ ruby -Itest test/remote/gateways/remote_zeus_test.rb
Loaded suite test/remote/gateways/remote_zeus_test
Started
.F
================================================================================
Failure:
  Response expected to succeed: <#<ActiveMerchant::Billing::Response:0x007fb429d0d8f8
   @authorization="TEST-021102-126376662",
   @avs_result=
    {"code"=>nil, "message"=>nil, "street_match"=>nil, "postal_match"=>nil},
   @cvv_result={"code"=>nil, "message"=>nil},
   @emv_authorization=nil,
   @error_code="failer_order",
   @fraud_review=nil,
   @message={:raw=>"failer_order", :status=>"failer_order"},
   @params={"raw"=>"failer_order", "status"=>"failer_order"},
   @success=false,
   @test=true>>
test_failed_capture(RemoteZeusTest)
test/remote/gateways/remote_zeus_test.rb:72:in `test_failed_capture'
     69:     response = @gateway.capture(@amount, initial_auth.authorization, (Date.today - 1.day).to_s.gsub('-', ''))
     70:
     71:     assert_success initial_auth
  => 72:     assert_success auth
     73:     assert_failure response
     74:     assert_equal false, response.authorization.nil?
     75:   end
================================================================================
..F
================================================================================
Failure:
  Response expected to succeed: <#<ActiveMerchant::Billing::Response:0x007fb429baf880
   @authorization="TEST-021116-130266675",
   @avs_result=
    {"code"=>nil, "message"=>nil, "street_match"=>nil, "postal_match"=>nil},
   @cvv_result={"code"=>nil, "message"=>nil},
   @emv_authorization=nil,
   @error_code="failer_order",
   @fraud_review=nil,
   @message={:raw=>"failer_order", :status=>"failer_order"},
   @params={"raw"=>"failer_order", "status"=>"failer_order"},
   @success=false,
   @test=true>>
test_successful_authorize(RemoteZeusTest)
test/remote/gateways/remote_zeus_test.rb:42:in `test_successful_authorize'
     39:     response = @gateway.authorize(@amount, initial_auth.authorization, Date.today.to_s.gsub('-', ''))
     40:
     41:     assert_success initial_auth
  => 42:     assert_success response
     43:     assert_equal false, response.authorization.nil?
     44:   end
     45:
================================================================================
F
================================================================================
Failure:
  Response expected to succeed: <#<ActiveMerchant::Billing::Response:0x007fb429b37650
   @authorization="TEST-021121-131236680",
   @avs_result=
    {"code"=>nil, "message"=>nil, "street_match"=>nil, "postal_match"=>nil},
   @cvv_result={"code"=>nil, "message"=>nil},
   @emv_authorization=nil,
   @error_code="failer_order",
   @fraud_review=nil,
   @message={:raw=>"failer_order", :status=>"failer_order"},
   @params={"raw"=>"failer_order", "status"=>"failer_order"},
   @success=false,
   @test=true>>
test_successful_capture(RemoteZeusTest)
test/remote/gateways/remote_zeus_test.rb:61:in `test_successful_capture'
     58:     response = @gateway.capture(@amount, initial_auth.authorization, Date.today.to_s.gsub('-', ''))
     59:
     60:     assert_success initial_auth
  => 61:     assert_success auth
     62:     assert_success response
     63:     assert_equal false, response.authorization.nil?
     64:   end
================================================================================
..

Finished in 42.64084 seconds.
--------------------------------------------------------------------------------
8 tests, 20 assertions, 3 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
62.5% passed
--------------------------------------------------------------------------------
0.19 tests/s, 0.47 assertions/s
```

**Comment by ShubhamGupta** [comment]
@ntalbott I have fixed the failing test cases. Thanks for posting the backtrace.

Issue: The gateway accepts a string parameter for `date` in format `yyyymmdd`. It tests the validity of date and rejects any past dates. Since, the gateway is very Japanese, there is no parameter for timezone and it treats the `date` accordingly (i.e. in JST). When you ran the test cases, it sent `Date.today` which was a past date for the gateway and the request failed. However, I was not getting any failing test case as I am in Japanese time zone and thus the current date was getting sent and the tests were always passing.

Fix: The gateway accepts current or future date (upto 62 days). Instead of sending current date, we are now sending a future date in test cases to avoid timezone issue with test cases.

We are good to merge this as our gateway class doesn't do any operations on `date`. It simply takes it as an `option` and sends it to the Zeus. There was no bug as per the `ZeusGateway` class as it never works on any date / time object in any way.

**Comment by jasonwebster** [comment]
Closing due to staleness. Feel free to reopen when the outstanding issues are resolved.

**Comment by johnnyshields** [comment]
@jasonwebster why are you closing this? It's ready to merge.

**Comment by jasonwebster** [comment]
It's been open for well over a year now with no action. I've closed all PRs over 14 months old automatically.

**Comment by johnnyshields** [comment]
Can someone merge it please?

**Comment by ShubhamGupta** [comment]
@jasonwebster There were a few improvements suggested by @ntalbott which have been fixed already. Please review.

**Pull request closed without merging**
