### PR TITLE
Update Rubocop to 1.14.0

### PR DESCRIPTION
**Pull request by almalee24**

### CODE REVIEW

**Comment by almalee24** [comment]
> @almalee24 did you use `bundle exec rubocop -a` to auto fix them?

Yes but it didn't do all of them so some I did manually

**Comment by aenand** [comment]
> > @almalee24 did you use `bundle exec rubocop -a` to auto fix them?
> 
> Yes but it didn't do all of them so some I did manually

Do you remember which rule styles you had to do manually?

**Comment by almalee24** [comment]
> > > @almalee24 did you use `bundle exec rubocop -a` to auto fix them?
> > 
> > 
> > Yes but it didn't do all of them so some I did manually
> 
> Do you remember which rule styles you had to do manually?

It definitely one fixing dig ones from response.dig(:code) to response[:code] and but I can't remember the other ones. I disabled the ones that caused the errors so rubocop so I didn't have to change those.

**Comment by bradbroge** [comment]
What do we need to do to get the automated tests running?

**Comment by DustinHaefele** [comment]
@bradbroge We need to update the ruby version, but this rubocop upgrade is a blocker on the ruby version upgrade.

**Comment by almalee24** [comment]
> What do we need to do to get the automated tests running?

You can run them local by `doing bundle exec rake test:local`

**Comment by almalee24** [comment]
I can't remember they manual changes I made but the following are changes that exist in the PR

- StringConcatenation: [Example](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-a6a72f43e29a1696815b33233d2e4ce415812bdaad4da0d3823e831e03c982cdL260)
- split('') -> split. [Example](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-df3ec34cccee29514637175dddc41caa9efcf743804bf93ee54cf20c9cd23762L34)
- SlicingWithRange. Ex: [-2..-1] -> [-2..] [Example](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-f921e3c2e2d761d7b1e7eeee6fc7e962bf391f967071ffcdf9644fac3743690bL44)
- transform_keys over map {...}.to_h. [Example](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-df3ec34cccee29514637175dddc41caa9efcf743804bf93ee54cf20c9cd23762L34)
- Removed redundant safe navigation: [Example](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-2fe4c5dc2bc356dd2e6868b85240d8813c52de787c799b52a99521f8b419fa71L303)
- Convert if-elsif to case-when: [Example](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-2f06ed86c4dd8c4e7e546d4b1aa4573d7edc2cd37eb97fb0afc753c26203724dL158)
- SingleArgumentDig. Ex: response.dig('resultCode') -> response['resultCode']. [Example](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-a7264544d772987646858e2b4287eb47f5e18340352a1d1ca4e2ad80c77a47c9L399)
- Duplicate branch. [Example](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-b931625cd2b4a6e6659c4686ec2d969197465dc6ec5e2c2c6bc62a29709b490eL182)
- InverseMethods: [Example](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-09f6a7e53e883c4ba646836318f9ff3e6ebe27b9a640f268b852a0503c2d5b9aL183)
- HashEachMethods: [Example](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-9a118a6517a1161d1a94431614cd9678a1cc7529ed984f739df42483f248bba0L237)
- IfWithBooleanLiteralBranches: [Example](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-18b55008deb6c59ef5f40f02ce91c1c29c89a1f8c9c5c20e5904b66d9f9b61c5L359)
- EmptyConditionalBody: [Example](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-8d8c05c07eec351f7a5f5a25147288b6020b4c4244e3e496684a9ebe395aa9c2L450)
- HashLikeCase: [Example](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-a193031782445501071c4a728ce7d0abb307ce662396ed700ff06e32df85bf00L448)
- Use compact instead of reject { |_k, v| v.nil? }. [Example](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-967580fe83557c926693c1738508b90dab816413cf0399cbdadc5b453b330d6bL512)
- Use chars instead of split(//). [Example](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-43e3885a841686759bc80d1eef678f3f17a44fb5f6bdf59f07c0e7c2660e0798L34)
- Use $stdout instead of STDOUT. [Example](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-49dcc70e309c6b71a65b45f1ca7b1ae38c18d5250972d15867305bb5d792b6e6L899)
- Remove empty block detected. [Example](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-f9120c0315e5a48cd44823bb1e2c5363f349e878b20b6790ac9fbed5182f17cdL98)
- Use each_key instead of keys.each. [Example](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-8b9eda3fe68cd0d757a6132fd235cc5ea5cdd16e1313674153a3fe906ad9c32bL170)

I did run `bundle exec rubocop -A` and when I do that again in a new branch these are the 65 changes that need to be manually changes

-  Lint/DuplicateBranch -> [Ex 1](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-ccd4c5f1fef5146efab6c2b090e08d36e3ddbd2be22e150f5bab0af901ec8e64L219), [Ex2](https://github.com/activemerchant/active_merchant/pull/5020/files), [Ex3](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-200727fc728e189315a6fd1157c4f15a46ac7552f8fc88ee4f0aa57568164f8fL260), [Ex4](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-b931625cd2b4a6e6659c4686ec2d969197465dc6ec5e2c2c6bc62a29709b490eL182), [Ex5](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-8a4316e5845041762c496e764edeb4a7b0a8316a069ba0b026e33d141410ff9bL341), [Ex6](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-f2e8031f865d35bb00d16a6b72f4e706a0f8dc7fba30e360e79453367dd716a0L242), [Ex7](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-b2e86850535eb9667ec61115229af835cd6da2be9018467e1bdb6e08e20ea3d7L207), [Ex8](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-c7f61a14622e345e672675d3409b74a629bbc9ee2a13a03d7dd5302cd43c3e1bL429), [Ex9](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-dea0ce2b9e99c8e44b9ebce48fd4e4b6e1ebff2213f567de381bd8c3c5f0c2a6L336), [Ex10](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-cab5f581bb6e483767353e21233786ef92ac4b4e0fb561a31427cfde76e00abeL298), [Ex11](lib/active_merchant/billing/gateways/qvalent.rb), [Ex12](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-8f17a82e2a38e71c76ad882d3c1a6a684606e41ba57cf9d484365a3f9b14f523L370), [Ex13](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-112bf5cda2d5d8493c57ff680ea291b1159c3f931f21d89027c5b47bd77fb417L113), [Ex14](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-137fc6f7bddf9a10ae6149ac50d9d5076e3786406ef8ddfcd46ea57fbe1091b9L426), [Ex15](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-45a7a9229d37bcd068d58c7100007ee2d76535064804126f6b7139fbc841425bL195), [Ex16](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-8540a6d5cb35da4fdd8ce628d87a65457672dff2e370114414c3dfb15f8bd7c0L147)
- Lint/Syntax: [Ex1](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-14bedd121d9bed1986ac79f2b06492ea82362f5286c6696d13cec7f8d09f519dL73)
- Style/HashLikeCase: [Ex1](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-52d41901687c123591c5982b8860301bca8244f605e26e1eee2950c04b9269e7L136), [Ex2](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-6c0866112152de13ba957b81e1b22fc6e2827c8c0aecc138fc796c7dec18fba8L759), [Ex3](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-085bb77b769e463068392d40ae9531b6d38672fe35458f3d3829876b2fa07bbbL246), [Ex4](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-a193031782445501071c4a728ce7d0abb307ce662396ed700ff06e32df85bf00L448), [Ex5](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-1c7c9bf7616efb927abaa9892e84d00964291a3187aabe6e2b71fc8db75d28cfL123), [Ex6](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-cab5f581bb6e483767353e21233786ef92ac4b4e0fb561a31427cfde76e00abeL284), [Ex7](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-2f06ed86c4dd8c4e7e546d4b1aa4573d7edc2cd37eb97fb0afc753c26203724dL176), [Ex8](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-e4f4d99aa26e9800d8136f890f5e187788b47b5182fc1d582fa533e430c6e998L273), [Ex9](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-967580fe83557c926693c1738508b90dab816413cf0399cbdadc5b453b330d6bL688)
- Style/StringConcatenation: [Ex1](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-3d484051c28096ad222ee0401a356a0b0743fb70b1e71ebefa0526c63ba44cb7L372)
- Lint/EmptyConditionalBody: [Ex1](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-8d8c05c07eec351f7a5f5a25147288b6020b4c4244e3e496684a9ebe395aa9c2L450)
- Lint/EmptyBlock: [Ex1](https://github.com/activemerchant/active_merchant/pull/5020/files#diff-f9120c0315e5a48cd44823bb1e2c5363f349e878b20b6790ac9fbed5182f17cdL98)

**Pull request closed without merging**
