### PR TITLE
Velocity gateway

### PR DESCRIPTION
**Pull request by ashishCetuG**
North American Bancard (NAB) is a credit card processing company that offers solutions for credit, debit, EBT, check conversion and guarantee, gift & loyalty cards and more. 
North American Bancard (NAB) provides a ruby gem ruby-sdk in https://github.com/nab-velocity/ruby-sdk. 
We are adding ruby-sdk gem to active merchant as a payment gateway.

Please refer this old pull request for reference. https://github.com/activemerchant/active_merchant/pull/1878.

### CODE REVIEW

**Comment by ashishCetuG** [comment]
Is there any modifications or changes that i need to make for this pull request.Please let me know for any kind of suggestion.

**Comment by ntalbott** [comment]
@ashishCetuG it's improving; you need to get `initialize` in-line with other gateways. Also, all gateway code should be in a single file, and as simple and fit-to-purpose as possible.

**Comment by ashishCetuG** [comment]
@ntalbott Modified initialize method and also optimized build xml methods of velocity gateway in a single file. Please go through this & provide any suggestions.

**Comment by zoxman-nabv** [comment]
Hello, any update on getting these changes reviewed and merged?

**Comment by zoxman-nabv** [comment]
@ntalbott Hi, could you please give us an update on this?

**Comment by zoxman-nabv** [comment]
@duff Could you please give us an update if @ntalbott is is too busy...?

**Comment by zoxman-nabv** [comment]
@ntalbott Any update on this? Thank you.

**Comment by vexilar** [comment]
Is there anything we can do to expidite this?  We have some clients waiting on this.

**Comment by ntalbott** [comment]
The best we can suggest is using a fork until it gets merged. We don't/can't give timelines or schedules for merging as maintainers.

**Comment by jasonwebster** [comment]
Closing due to staleness. Feel free to reopen when the outstanding issues are resolved.

**Pull request closed without merging**
