### PR TITLE
visanet peru gateway response message

### PR DESCRIPTION
**Pull request by shasum**
@duff 

- meaningful gateway message lookup in multiple response fields
- currency conversion from cents to $$.cc before passing to gateway

### CODE REVIEW

**Comment by duff** [comment]
@shasum I'm thinking it would be great to split up these into 2 PR's - one for the error messages and one for the currency fix.  The error messages part is looking good.  

I'm mulling some on the currency part.  Does their docs say anything about it?  

It sounds like we might want to do something that we do for a number of gateways specifying a different `money_format`.  Example:

https://github.com/duff/active_merchant/blob/master/lib/active_merchant/billing/gateways/authorize_net.rb#L13

Then the `amount` method uses that:

https://github.com/duff/active_merchant/blob/master/lib/active_merchant/billing/gateway.rb#L234

**Comment by shasum** [comment]
@duff 

crazy me. I stared straight into the `amount()` method while I was doing this piece and yet failed to realize the `:dollars` money format does exactly what I wanted 😄 . thanks for pointing it out. I'll refactor the currency part and submit separate PRs.

**Comment by duff** [comment]
Excellent.  Thanks @shasum !

**Comment by shasum** [comment]
@duff this PR now fixes only the message part

**Comment by duff** [comment]
@shasum Looking good.  2 little things.  We're trying to lessen our dependence on Active Support by using the `blank?` method less.  Eventually we'd like to eliminate the dependency altogether.  Instead of `blank?`, we've been using `empty?`.  Examples:

https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/authorize_net.rb#L6

https://github.com/activemerchant/active_merchant/blob/master/lib/active_merchant/billing/gateways/authorize_net.rb#L457

Also, it would be great if you could squash it down to one commit.

**Comment by shasum** [comment]
@duff emptied and squashed

**Pull request closed without merging**
