### PR TITLE
Add support for Discover Protect Buy Program in Orbital gateway

### PR DESCRIPTION
**Pull request by priceline-rosenfeld**

### CODE REVIEW

**Comment by priceline-rosenfeld** [comment]
Hi, could someone please review this PR?

**Comment by aenand** [comment]
Hi @priceline-rosenfeld do you have any documentation to support this change?

**Comment by priceline-rosenfeld** [comment]
Hi @aenand, yes I do have some documents to support this change, but unfortunately they are confidential by J.P. Morgan. But everyone working with Orbital should have access to such documents.

DPB stands for the Discovery Protect Buy program.

This changed is supported by what is stated on pages 39 and 199 of the "Orbital Gateway XML Interface Specification 7.9.0.1.pdf" document.

**Comment by cgriego** [comment]
@aenand What else is needed for this?

**Comment by aenand** [comment]
Hi @cgriego I've transitioned off the team that was working on this PR. I will file a request for someone to take a look at this!

**Comment by bradbroge** [comment]
I'll be reviewing this today/Tuesday, and I should have an update next week for when we can merge it.

**Comment by priceline-rosenfeld** [comment]
Thank you.

**Review by bradbroge — APPROVED** [review]
Sorry for the slow response. We plan to merge this next Wednesday (11 September).

**Comment by priceline-rosenfeld** [comment]
Awesome, thanks!

**Pull request merged**
