### PR TITLE
Add firstdata E4 Version 14

### PR DESCRIPTION
**Pull request by wedstar**
hi guys, im adding the firstdata E4 for v14, it's pretty straight forward compare to v11

what's in here but not in v11 
1. Support HMAC authentication as per https://support.payeezy.com/hc/en-us/articles/203731149-API-Security-HMAC-Hash
2. Replaced Property:
VerificationStr1 replaced with Address element
VerificationStr2 replaced with CVDCode

this is my first contribution for this project, please let me know if i miss something or any thoughts on this

### CODE REVIEW

**Comment by ntalbott** [comment]
@wedstar I'd prefer this was just an update to the existing adapter; I don't really want a new gateway class for every version of API's unless it's really a new version.

What benefits if any does this new version of E4 provide?

**Comment by wedstar** [comment]
hi @ntalbott thank you
i was thinking to update the existing adapter or at least inherit from the original adapter.
the annoying part is in v14 some of elements has been renamed it, it's not really backward compatible
so i thought to treat this as a separate adapter would be suitable,

to update the existing adapter, there will be lots of if-conditions something like
```if version == 11
      xml.tag! "VerificationStr2", credit_card.verification_value
    else
       xml.tag! "CVDCode", credit_card.verification_value
    end
```
please advise

**Comment by wedstar** [comment]
hi @ntalbott 
do i need anything else to get this PR accepted? thank you

**Comment by ntalbott** [comment]
@wedstar so HMAC is required for v12+? Ugh...

Does v14 support Transarmor?

**Comment by jasonwebster** [comment]
Closing due to staleness. Feel free to reopen when the outstanding issues are resolved.

**Pull request closed without merging**
