### PR TITLE
$0 Auth on Checkout gateway

### PR DESCRIPTION
**Pull request by jessiagee**

### CODE REVIEW

**Review by naashton — APPROVED** [review]
Noice 👍

**Comment by naashton** [comment]
I'm so confused as to how you ended up with a commit from Leila from May 2019.

**Comment by jessiagee** [comment]
@naashton It somehow got pulled in from the spreedly/active-merchant fork that I made earlier 🤷🏻‍♀️  Git decided it wanted that to come in too.

**Comment by jessiagee** [comment]
Added a remote test from @therufs 's suggestion

**Review by InPermutation — APPROVED** [review]
👍

**Pull request merged**
