### PR TITLE
Vantiv Express: Add CardPresentCode, PaymentType, SubmissionType

### PR DESCRIPTION
**Pull request by esmitperez**
Fixes Rubocop rules-violation

CE-769

Unit:
22 tests, 99 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Remote:
24 tests, 67 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

### CODE REVIEW

**Comment by leila-alderman** [comment]
Hey @esmitperez! While you're still onboarding, you should be requesting reviews from `spreedly-customer-eng` since they have the most context for this work.

**Comment by naashton** [comment]
I'm only seeing a deleted line in this. Maybe you closed the wrong PR?

**Comment by esmitperez** [comment]
Just a line deletion to make rubocop happy. My IDE missed it for some reason but Travis CI caught it. Found no easy way to retrofit since I already had other branches/merges going on locally

**Comment by naashton** [comment]
Whoops, I see that now that I actually *read* your PR. My bad!

**Comment by therufs** [comment]
yay for appeasing the rubocop :D

**Comment by curiousepic** [comment]
FYI: It looks like this PR was an update to the primary changes described in the message that went in with this already-merged commit: https://github.com/activemerchant/active_merchant/commit/9c3b137b0dece884434588eeb87b479f68a9088f

**Pull request closed without merging**
