### PR TITLE
Use Authorize.Net's XML API

### PR DESCRIPTION
**Pull request by ntalbott**
Work in progress. Supercedes #1219.

TODO:
- [x] Figure out mapping for `x_solution_id`.
- [x] Figure out how to pass currency code (`x_currency_code`).
- [x] Match semantics of old `Response#authorization`.
- [x] Match semantics of old `Response#params` as closely as possible.
- [x] Replace `AuthorizeNetGateway` with `AuthorizeNetXmlGateway`.
- [x] Flatten unit and remote tests.

### CODE REVIEW

**Comment by bcackerman** [comment]
@ntalbott Any examples how to use the solution id to create a transaction?  

Do I put it in here?
```
ActiveMerchant::Billing::AuthorizeNetGateway.new(
          login:      @login,
          password:   @password
        )
```

Or do I add it to the `gateway.purchase(amount, credit_card, options)` options? Just looking for an example, thanks!

**Comment by ntalbott** [comment]
@bcackerman I think you set it at the class level: `ActiveMerchant::Billing::AuthorizeNetGateway.application_id = "spreedly"`.

**Comment by bcackerman** [comment]
Ah, like this?
```
ActiveMerchant::Billing::AuthorizeNetGateway.new(
          login:      @login,
          password:   @password,
          application_id: ENV['AUTHORIZE_NET_SOLUTION_ID']
        )
```

**Comment by bcackerman** [comment]
Hmm, doesn't seem to be working @ntalbott Any other ideas?

**Pull request closed without merging**
