### PR TITLE
Adding TRXservices Gateway

### PR DESCRIPTION
**Pull request by fourfour**
This PR adds the TRXServices Gateway.

http://www.trxservices.com

Transaction Services (TrxServices) is a leading provider of payment processing services.  TrxServices is an advanced provider of debit card and credit card acceptance in the U.S. dedicated exclusively to the small-to-medium merchant market.

### CODE REVIEW

**Comment by fourfour** [comment]
He guys. I was checking in to see if you had a chance to review our pull request. We have a couple of clients that are looking to use this integration.

Cheers.
-eric

**Comment by naturalstacks** [comment]
Just following up on this pull request. It's been hangin around since Nov 2015. We would really love to get this integrated. Is there anything we can do to help?

Thanks!

**Comment by jasonwebster** [comment]
Closing due to staleness. Feel free to reopen when the outstanding issues are resolved.

**Comment by naturalstacks** [comment]
What outstanding issues need to be resolved? I haven't seen any comments regarding this since I submitted it. @jasonwebster

**Comment by jasonwebster** [comment]
Hi! Thanks for commenting! I automatically closed all PRs that have been open for more than 14 months. I see this one's had some more recent activity, so it probably shouldn't have been in there.

**Comment by davidsantoso** [comment]
Hi @fourfour and/or @naturalstacks- going through and pruning PRs and issues and looks like this is more or less ready to merge. Wondering if you'd be able squash into a single commit and rebase on master? I'll take another look once that happens. Thanks!

**Comment by fourfour** [comment]
Hi @davidsantoso 
Sorry about the late response. Can we reopen this and I will push up a single commit.

Thanks!!
-Eric

**Comment by fourfour** [comment]
@jasonwebster @davidsantoso 

Hey guys. I merged the commits and rebased to master. Just popped in on a new PR as this was closed. https://github.com/activemerchant/active_merchant/pull/2438

Any chance you guys could do this ASAP. We have a $2m deal with a client that uses Shopify and want to switch to our service. But, we need it done by tomorrow. I will buy you guys a beer or a pony, whatever you want :)

**Comment by jasonwebster** [comment]
Hi,

Just to be perfectly clear with the expectations here, ActiveMerchant and Shopify are quite separate. Yes, Shopify uses ActiveMerchant, and we contribute to it as well. Having an ActiveMerchant integration is great--it eases implementation for many developers, but it is absolutely no guarantee that the gateway will be available to use in Shopify.

**Comment by fourfour** [comment]
Hmm gotcha. So Shopify doesn't use ActiveMerchant as a whole? They limit the gateways they allow?

Regardless, let's get this merged in AM. Thanks!

**Pull request closed without merging**
