### PR TITLE
Global Collect: Fix customer data field structure

### PR DESCRIPTION
**Pull request by curiousepic**
Previously, many customer data fields were not being properly placed in
the customer envelope.

Remote:
16 tests, 37 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

Unit:
17 tests, 79 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed

### CODE REVIEW

**Comment by nfarve** [comment]
Weird failures on Travis. Can we add a unit test to check that the fields are now being passed properly?

**Comment by bpollack** [comment]
Second on having a test for this. Just unit ought to be fine.

**Comment by bpollack** [comment]
Travis is fixed. The workers we got just looked like they were bad workers, so I kicked off the bad builds again, and sure enough, clean pass.

**Comment by curiousepic** [comment]
Altered `test_successful_authorization_with_extra_options` to check for structure.

**Pull request closed without merging**
