### PR TITLE
Garanti Test Url Fix

### PR DESCRIPTION
**Pull request by cbilgili**
It uses Garanti default test url in test environment

### CODE REVIEW

**Comment by aprofeit** [comment]
Thanks for the PR. Do you have a link to the documentation just so I can verify that's the correct test url?

**Comment by cbilgili** [comment]
Actually I got that email from support of bank. But please could you try that to see response of bank?

**Comment by ntalbott** [comment]
@cbilgili it looks like the credentials for Garanti aren't working - do you have working credentials available?

**Comment by cbilgili** [comment]
@ntalbott Which credentials do you need?

**Comment by ntalbott** [comment]
@cbilgili a working set of these so I can run the remote tests:

https://github.com/activemerchant/active_merchant/blob/master/test/fixtures.yml#L276-L280

**Comment by cbilgili** [comment]
@ntalbott I don't have but asked to bank now.

**Comment by cbilgili** [comment]
@ntalbott  I have updated fixtures and valid credit card data according to bank.

**Comment by aprofeit** [comment]
@cbilgili Was able to run the remote tests with those credentials, thanks!

**Pull request closed without merging**
