### PR TITLE
Test against Ruby 2.7

### PR DESCRIPTION
**Pull request by casperisfine**
It seems to work fine, but it was emitting quite a few warnings.

### CODE REVIEW

**Comment by casperisfine** [comment]
CI is failing, but I have the same errors on master if I run the test suite locally.

**Comment by casperisfine** [comment]
@curiousepic @molbrown @pi3r could one of you take a look please?

**Comment by curiousepic** [comment]
We have another outstanding PR for adding the new versions, and removing 2.3 and 2.4: https://github.com/activemerchant/active_merchant/pull/3631
I think we're planning on making the changes Bart suggested there.

Or is this a different/preferred approach?

**Comment by casperisfine** [comment]
No, I simply didn't see it. #3631 seems fine, but you might want to get the `YAML.safe_load` changes.

**Comment by casperisfine** [comment]
Closing in favor of https://github.com/activemerchant/active_merchant/pull/3656

**Pull request closed without merging**
