### PR TITLE
Add unmaskExpirationDate option to AuthorizeNetCimGateway 

### PR DESCRIPTION
**Pull request by RamilGilmanov**
Add support for recently introduced "unmaskExpirationDate" option for AuthorizeNetCimGateway "get_customer_payment_profile" request

Reference: http://developer.authorize.net/api/reference/index.html?utm_campaign=November%202015%20Developer%20Newsletter&utm_medium=email&utm_source=Eloqua&elq=bd005706e5e048c5b532a59630590118&elqCampaignId=310&elqaid=454&elqat=1&elqTrackId=f3687d9f5ed34606a56edfb6baf22562#customer-profiles-get-customer-payment-profile

### CODE REVIEW

**Comment by RamilGilmanov** [comment]
@aprofeit @ntalbott @duff 
Could you please take a look?

**Comment by aprofeit** [comment]
lgtm, will wait for @ntalbott or @duff to chime in as well.

**Comment by ntalbott** [comment]
The AuthorizeNetCim gateway is deprecated and will be gone in the next major revision of ActiveMerchant. So I don't really care :smiling_imp:.

**Comment by RamilGilmanov** [comment]
@ntalbott are you serious? what is the reason for that?
Can we have this merged in some minor version then?

**Comment by RamilGilmanov** [comment]
Sorry, it's been already merged! Thanks!

**Comment by duff** [comment]
@RamilGilmanov Yup, he's serious! :)  You can now use `store` functionality in the `AuthorizeNetGateway`:

https://github.com/activemerchant/active_merchant/commit/8c00b3841e81c3e6a0a5a36c7d640e3eed5004ee

**Pull request closed without merging**
